host_ha:
  host: https://XXXXXXXXXXXXXXX:8123
  api_password: XXXXXXXXXXXX
#
#
pulsanti_telecomando:

# ESEMPIO DI CONTROLLO ALTERNATO
# UN PULSANTE ALTERNATIVAMENTE VIENE USATO PER 2 SERVIZI DISTINTI

- comando_alternato:
    codice: '3772782313'
    nome_pulsante: uscite
    servizio_da_eseguire: servizio_uno
    servizio_uno:
      servizio: script.turn_on
      entita: script.cinema_salotto_on
    servizio_due:
      servizio: scene.turn_on
      entita: scene.fine_cinema
      
# ESEMPIO DI CONTROLLO DELLE LUCI

- comando:
      nome_pulsante: "giallo"
      codice: "3772819543"
      servizio: light.turn_on
      dati:
        luminosita: "100"
        colore: yellow
      entita: light.mobile_soggiorno
- comando:
      nome_pulsante: "rosso"
      codice: "3772790473"
      servizio: light.turn_on
      dati:
        colore: red
      entita: light.mobile_soggiorno
- comando:
      nome_pulsante: "blu"
      codice: "3772803223"
      servizio: light.turn_on
      entita: light.mobile_soggiorno
      
#  ESEMPI DI COMANDO DI ESECUZIONE DI UN SERVIZIO DI HA

- comando:
      nome_pulsante: "1"
      codice: "3772784863"
      servizio: switch.toggle
      entita: switch.luce_entrata
- comando:
      nome_pulsante: "5"
      codice: "3772813423"
      servizio: script.turn_on
      entita: script.arrivo_papa
      
# ESEMPIO DI DIMMER
# UN PULSANTE AUMENTA LA LUMINOSITA DI UNA LUCE ED UNO LA DIMINUISCE

- dimmer:
      nome_pulsante: "volume +"
      codice: "3772833823"
      skip: "40"
      entita: light.mobile_soggiorno
      direzione: "+"
- dimmer:
      nome_pulsante: "volume -"
      codice: "3772829743"
      skip: "40"
      entita: light.mobile_soggiorno
      direzione: "-"
#
- comando:
      nome_pulsante: "2"
      codice: "3772817503"
      servizio: switch.toggle
      entita: switch.luce_principale
- comando:
      nome_pulsante: "3"
      codice: "3772801183"
      servizio: switch.toggle
      entita: switch.luce_atrio
- comando:
      nome_pulsante: "4"
      codice: "3772780783"
      servizio: switch.toggle
      entita: switch.luce_cucina

- comando:
      nome_pulsante: "6"
      codice: "3772797103"
      servizio: light.toggle
      entita: light.mobile_soggiorno
- comando:
      nome_pulsante: "7"
      codice: "3772788943"
      servizio: switch.toggle
      entita: switch.luce_cucina
- comando:
      nome_pulsante: "8"
      codice: "3772821583"
      servizio: switch.toggle
      entita: switch.luce_cucina
- comando:
      nome_pulsante: "9"
      codice: "3772805263"
      servizio: light.turn_off
      entita: light.mobile_soggiorno
- comando:
      nome_pulsante: "EXIT"
      codice: "3772822603"
      servizio: scene.turn_on
      entita: scene.fine_cinema
- comando:
      nome_pulsante: "verde"
      codice: "3772786903"
      servizio: light.turn_on
      dati:
        #luminosita: "100"
        colore: green
      entita: light.mobile_soggiorno


 
